[package]
name = "bouncer-app"
description = "Bouncer desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
bouncer-core = { path = "../core" }
tauri = { version = "2.12.1", features = [] }
